
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace PredictiveMaintenance_Console
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            PredictiveMaintenanceModel.ModelInput sampleData = new PredictiveMaintenanceModel.ModelInput()
            {
                Product_ID = @"M14860",
                Type = @"M",
                Air_temperature = 6981F,
                Process_temperature = 9086F,
                Rotational_speed = 1551F,
                Torque = 828F,
                Tool_wear = 45000F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = PredictiveMaintenanceModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n\n");


            Console.WriteLine($"Product_ID: {@"M14860"}");
            Console.WriteLine($"Type: {@"M"}");
            Console.WriteLine($"Air_temperature: {2981F}");
            Console.WriteLine($"Process_temperature: {3086F}");
            Console.WriteLine($"Rotational_speed: {1551F}");
            Console.WriteLine($"Torque: {428F}");
            Console.WriteLine($"Tool_wear: {0F}");
            Console.WriteLine($"Machine_failure: {0F}");


            Console.WriteLine($"\n\nPredicted Machine_failure: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
